//ui
export const FETCHING = 'FETCHING';

//INITAL LIST
export const FETCH_CLASSES = 'FETCH_CLASSES';
export const FETCH_SUBCLASSES = 'FETCH_SUBCLASSES';

//CLASS DESCRIPTION
export const FETCH_DESCRIPTION = 'FETCH_DESCRIPTION';

//SUBCLASS FLAVOUR
export const FETCH_FLAVOUR = 'FETCH_FLAVOUR';
export const CLEAR_FLAVOUR = 'CLEAR_FLAVOUR';

//SPELLS
export const FETCH_SPELLS_INIT = 'FETCH_SPELLS_INIT';

export const FETCH_SUBCLASS_SPELLS = 'FETCH_SUBCLASS_SPELLS';
export const CLEAR_SUBCLASS_SPELLS = 'CLEAR_SUBCLASS_SPELLS';

export const FETCH_CLASS_SPELLS = 'FETCH_CLASS_SPELLS';
export const CLEAR_CLASS_SPELLS = 'CLEAR_CLASS_SPELLS';
